### ISSUE TITLE
Does poise-service replace the builtin service?

### ISSUE THREAD

**Issue by rberger** [poise/poise-service#1]
Its not clear (to me)  if poise-service replaces or complements the builtin service resource.

I.E. could I use poise-service to create the init/upstart/systemd/etc service on a node and then refer to it with the standard service resource?

I'm mainly thinking of things that do a notify service restart. Would I have to change those to nofity poise-service?

**Comment by coderanger** [comment]
The readme now has a section on this: https://github.com/poise/poise-service#how-is-this-different-from-the-built-in-service-resource
