### ISSUE TITLE
Recent changes may have broken existing Centos 6 services

### ISSUE THREAD

**Issue by neilmunro** [poise/poise-service#14]
The fix for [Issue #8](https://github.com/poise/poise-service/issues/8) **Process.uid = some_user` not working on Centos 6 + upstart** seems to be preventing my service from running.

The commit : https://github.com/poise/poise-service/commit/0463bfcc402abfb6f4ee4490bc1909ba18134a71

My service was already running using poise service and this change causes the service to stop running as **root** and start running as the 'correct' user.  This means my service no longer has access to it's data files because they were created as **root**.

I'm using consul-cookbook which has

> depends 'poise-service', '~> 1.0'

which seems right to me but assumes patch version bumps won't be breaking.

Is it possible to retroactively make this change a minor or major version bump if it is a breaking change?

**Comment by coderanger** [comment]
This was a security fix so it gets shipped in the next bugfix release regardless of compat as any breakage is a sign of underlying security problems. Sorry for the inconvenience.

The old code set the UID but not the EUID which had some impact on stuff like file ACL handling as you've noticed. You'll need to fix them manually, there was no way to automate it.
