### ISSUE TITLE
undefined method `never_reload' for PoiseService::Resources::PoiseService::Resource

### ISSUE THREAD

**Issue by gretel** [poise/poise-service#16]
following the doc i stumbled into another issue:

```
  poise_service 'srv' do
    command 'somecmd'
    user 'someuser'
    directory '/somedir''
    provider :upstart
    never_reload true
  end
```
`chef 12.5.1` running on `ubuntu 12.04` including `upstart 1.5`. regards

**Comment by coderanger** [comment]
Things like `never_reload` are not resource properties, they are provider options. You can set it like `options never_reload: true`, or for a single provider `options :providername, never_reload: true`. See the section on provider options for more info, they can also be set via the `poise_service_options` resource or via node attributes.

**Comment by gretel** [comment]
ah i get it, sorry, doh. thanks for clarifying. how about a gitter chat? i'd have asked there first.

**Comment by coderanger** [comment]
I already sit in #chef IRC, Hangops Slack, Chef Brigade Slack, and Chef Success Slack. Last thing I need is a new chat system to watch :P

**Comment by gretel** [comment]
alright, thanks a lot!
