### ISSUE TITLE
WARN: Cloning resource attributes for group[graphite] from prior resource (CHEF-3694)

### ISSUE THREAD

**Issue by gretel** [poise/poise-service#18]
just a warning on `chef-12.06`:

```
         * poise_service_user[graphite] action create[2016-01-14T14:42:49+00:00] WARN: Cloning resource attributes for group[graphite] from prior resource (CHEF-3694)
       [2016-01-14T14:42:49+00:00] WARN: Previous group[graphite]: /tmp/kitchen/cache/cookbooks/xpl_graphite_ng/recipes/_user.rb:28:in `from_file'
       [2016-01-14T14:42:49+00:00] WARN: Current  group[graphite]: /tmp/kitchen/cache/cookbooks/poise-service/files/halite_gem/poise_service/resources/poise_service_user.rb:104:in `create_group'
```

**Comment by coderanger** [comment]
You are trying to use `poise_service_user` to create the group while also creating it elsewhere in your recipe code. Fix that.

**Comment by gretel** [comment]
i don't create the group anywhere else but going to revert to plain `user` resource.

**Comment by coderanger** [comment]
You can see the other location in the warning: `xpl_graphite_ng/recipes/_user.rb` line 28.

**Comment by gretel** [comment]
ah, i was expecting that resource to add the user only.. thanks!

**Comment by coderanger** [comment]
If you set `group nil` it won't make the group.

**Comment by gretel** [comment]
`gid new_resource.group if new_resource.group` - thanks for the hint!
