### ISSUE TITLE
Poise does not notice an existing startup file

### ISSUE THREAD

**Issue by jkugler** [poise/poise-service#20]
I am using the Collectd cookbook (https://github.com/bloomberg/collectd-cookbook) which uses poise-service to configure the service files for collectd.  However, when collectd is installed, it already has a SysV init file /etc/init.d/collectd. This file is enabled by default, as that is what a Debian style (Ubuntu in this case) installation does. Then poise-service is called by the collectd cookbook and poise-service creates and enables a service file in /etc/init/collectd.  This then causes two copies of collectd to be started, a very undesirable outcome.

Poise needs to determine if there is already an existing service file for the given service, and not create a new one if there is. At the very least, it should stop/disable the other service file if it is going to create and enable its own.

**Comment by coderanger** [comment]
This is out of scope for poise-service. If something is being installed from system packages it should ensure it nukes the distro-provided files: https://github.com/poise/poise-monit/blob/master/lib/poise_monit/monit_providers/system.rb#L64-L75

I'm working on some better generic tools for that, right now it's being handled one-off.

**Comment by jkugler** [comment]
@coderanger Thanks for taking a look.  Still thinking this through. The stated goal of poise-service is so that the cookbook writer doesn't have to worry about the init system. If they have to have logic in their code to 'delete init file X if distro Y, delete init file A if distro B' etc, then they are still having to worry about the init system. Whereas if poise-service simply used the already provided init file that came with the distro's package, then the cookbook author wouldn't have to worry about disabling it. At least that's my impression. :)

**Comment by coderanger** [comment]
The problem of distro-packaged `/etc` files is much broader than just init configs. For example, Ubuntu auto-starts services after install in a way poise-service can't know about unless it tried to enumerate every possible way a distro can start things. This is one of many reasons you shouldn't be using distro packages for most services in favor of simpler installers (notably the thing I linked is not the default provider for monit). The Chef resource model doesn't allow for this kind of "enumerate all possible providers to check if something was in use".

**Comment by coderanger** [comment]
I agree it is gross, but distro packages are broken in so many ways it is difficult to work around all of them without making everything terrible.
