### ISSUE TITLE
Berkshelf barfs because there's no metadata in this cookbook.

### ISSUE THREAD

**Issue by st33v** [poise/poise-service#21]
Berks can't seem to make heads or tails of this cookbook:

_Fetching 'poise-service' from https://github.com/poise/poise-service.git (at master)
The resource at '/var/folders/3f/s9k_mjgj5dl4ssfgnmnyqdr8dv569_/T/d20160218-33615-1ranu8q' does not appear to be a valid cookbook. Does it have a metadata.rb?_

the answer, of course is that there is indeed no metadata.rb. 

Am I missing something or should I submit a PR with the metadata?

**Comment by coderanger** [comment]
This cookbook, and all my cookbooks these days, is a Halite-based gem. It gets converted to a cookbook when I push releases to supermarket. If you need to run a pre-release version, see https://github.com/poise/halite#using-a-pre-release-version-of-a-cookbook

**Comment by st33v** [comment]
Oh, neat. I'll have to check out Halite.

thanks for the explanation.
