### ISSUE TITLE
poise_service on xenial 16.04 is triggering upstart rather than systemd in the marathon cookbook.

### ISSUE THREAD

**Issue by elijah** [poise/poise-service#26]
Hi Noah - leaving you a note here so you know that I filed a bug on the marathon cookbook.

https://github.com/mdsol/marathon_cookbook/issues/45

Not sure whether that bug is 'actually' a thing in poise_service or in Chef::Platform::ServiceHelpers, rather than something that could be forcibly worked around in Marathon.  I read through the poise_service code for a while and decided that I am not quite smart enough to understand all of what's going on... would appreciate some help, for sure.  :)

best,

--e

**Comment by coderanger** [comment]
Yeah, I delegate to `service_resource_providers` for the three main providers. Can you check on the machine if https://github.com/chef/chef/blob/master/lib/chef/platform/service_helpers.rb#L101-L102 works by hand?

**Comment by coderanger** [comment]
I just tested using Rackspace's Ubuntu 16.04 image and systemd support works as expected and is the default. Maybe this is 16.04 inside Docker? Systemd doesn't like to run inside Docker usually, though it can be convinced if you yell at it enough. I would recommend setting the `:dummy` provider for tests though, just to avoid all of those issues.

**Comment by elijah** [comment]
Unfortunately, no - this is a real, physical Dell R710, installed from a
USB drive with the ubuntu miniiso burned onto it, that I intend to set up
as a docker/mesos test host.  ;-)  Perhaps of value here is that the
machine is otherwise pretty much empty, so I can get away with nuking it if
I want to validate that nothing I've done manually (playing with cadvisor,
pihole, elasticsearch images) has fudged things up.

elw@pavlov:~$ cat /proc/1/comm
systemd

I'll take a look at those platform bits inside chef tomorrow and see if i
can get to the bottom of what's going on here.  I would very much like to
know, and I can probably make time this week.  ;-)

best,

--e

**Comment by coderanger** [comment]
That should definitely be working then. If you run `chef-client -l debug` you should see the messages about which providers are enabled for the `poise_service` resource, that might help.

**Comment by elijah** [comment]
It turns out that I was looking at the master branch of mdsol's marathon_cookbook while develop is what was coming down from supermarket -- whoops.

Now I see that develop has EXPLICIT hardcoding of the upstart provider in it... which I'm about to go rip out and submit patches to those guys so they can support 16.04.  

Whee!  Sorry for the confusion -- I certainly just got egg on my face.  And thanks for answering on the way into a long holiday weekend - that was very much appreciated.

**Comment by coderanger** [comment]
No worries, I wouldn't have been surprised if it was broken so at least now I've tested it :D
