### ISSUE TITLE
What's the best way to reload every time ? 

### ISSUE THREAD

**Issue by dorongutman** [poise/poise-service#27]
I need to setup the service on the first time the machine starts (and also if something is changed in the config file for example) and have the service reload every time I deploy.

What's the way of achieving this ? 
Should I use `action [:enable, :reload]` in the definition of the poise_service?

**Comment by coderanger** [comment]
Sure, that would do it. Works just like any other Chef resource. That's a weird requirement though, I would probably set up the reload to be based on notification triggers. If you check out the application cookbook(s) they have some nice stuff to auto-reload on any deployment change.
