### ISSUE TITLE
Allow to specify the pid file in upstart

### ISSUE THREAD

**Issue by dorongutman** [poise/poise-service#28]
For my application logic (unicorn zero-downtime logic), I'm saving the pid in a specific file.
I need upstart to take the pid from that file, and not save it on its own.

**Comment by coderanger** [comment]
Upstart only kind of supports this use case, see http://upstart.ubuntu.com/cookbook/#expect. I _think_ setting `expect daemon` can work with this but I don't think Unicorn has its own daemonization code that I would want to use. I see you also opened a similar issue for Runit, I'm afraid this mode of HUP-induced forking is very difficult to support in modern init systems (it was mostly designed for the init.d era). The approach taken by HAProxy was to make a [tiny wrapper program that handles the reload](https://github.com/horms/haproxy/blob/master/src/haproxy-systemd-wrapper.c), I would recommend doing something similar.

**Comment by coderanger** [comment]
Closing this out as something that requires application support or changing the Upstart configuration template.
