### ISSUE TITLE
Issue converging resource/provider using service mixin.

### ISSUE THREAD

**Issue by johnbellone** [poise/poise-service#3]
I am having an issue [converging the issue/provider](https://gist.github.com/johnbellone/0fb2b30ea12f5c44e7e6) that I re-wrote for the [collectd cookbook](https://github.com/johnbellone/collectd-cookbook/blob/master/libraries/collectd_service.rb).

**Comment by johnbellone** [comment]
This is using poise 2.0.0 and poise-service 1.0.1.

**Comment by coderanger** [comment]
After much mutual debugging, tracked this down to https://github.com/chef/chef/issues/3485.

Workaround is to use `guard_interpreter :default` on any resource using a command-based not_if/only_if.

**Comment by coderanger** [comment]
This is now patched upstream and will be included in 12.4 I think.
