### ISSUE TITLE
Undefined method pid_file

### ISSUE THREAD

**Issue by Esya** [poise/poise-service#30]
Hi,

When using the latest released version (1.3.1), when trying to use `pid_file` I get : 

```
undefined method `pid_file' for PoiseService::Resources::PoiseService::Resource
```

Here is my service declaration :

```
poise_service 'servicename' do
  command 'mycommand -d -p /tmp/mypidfile.pid'
  pid_file '/tmp/mypidfile.pid'
  action [:enable, :start]
  ignore_failure true
  provider :sysvinit
end
```

Am I missing something here? Thanks

**Comment by coderanger** [comment]
`pid_file` is a provider option, which is a little different from a resource property. The short version is you can do `options pid_file: '/tmp/mypidfile.pid'` and it will probably work for your case :) When you get into more generic-y usage of poise-service it can get a lot fancier.

**Comment by coderanger** [comment]
Closing this out, the correct syntax is shown above.
