### ISSUE TITLE
How can i create a service without starting or enabling it?

### ISSUE THREAD

**Issue by koertkuipers** [poise/poise-service#32]
Apologies, this is not an issue, really more a feature request or a question.
I would like to be able to create a service without it automatically starting or being enabled at server reboot. Sort of like:
```
pose_service 'myservice' do
  command '...'
  action :create
end
```
Basically i would like to call create_service without getting into enable_service or action_start. Is this possible?
Thanks!

**Comment by coderanger** [comment]
No, this is not part of the API. The `poise_service` abstraction was built to be more convergence-oriented than the core `service` resource. As such, `:enable` is the convergent statement "Service for X should be running" and likewise for `:disable`. There are some tweakable options like `never_restart` and `never_reload` to control certain situations but enable will always create+start.

**Comment by inhumantsar** [comment]
Well, guess I can't use this to bake AMIs then...

**Comment by coderanger** [comment]
You can make AMIs just fine, just enable and then stop the service. Or leave it running since it doesn't generally matter.

**Comment by inhumantsar** [comment]
Some services can't / shouldn't be started until they're in their target environment though. eg: applications that perform a bunch of database migrations and seeding on first launch, then expect to find that db again on subsequent launches. (For the record, I think those applications are stupid and frustrating, but I've got to support them regardless.)

What I'm trying to say is that "doesn't generally" != "always".

**Comment by coderanger** [comment]
Sure, for something that specialized you could make a tiny provider subclass that stubs `action_start` pretty easily.
