### ISSUE TITLE
allow greater flexibility for commands

### ISSUE THREAD

**Issue by grimm26** [poise/poise-service#38]
I have some processes that I manage with sysvinit and systemd that need a command run to issue a reload and stop.  I need to be able to specify the reload (ExecReload) and stop (ExecStop) commands instead of just providing a signal.

**Comment by coderanger** [comment]
The `poise_service` resource is very opinionated on purpose, as this is required to ensure things work equally on all service managers. As such this feature cannot be supported directly. For one-offs you can use provider options to override some bits, for example you can use your own systemd unit template and provide command overrides there. If you want to actually use all the features of systemd, there are several excellent systemd cookbooks out there.
