### ISSUE TITLE
Ability to override service template's cookbook.

### ISSUE THREAD

**Issue by johnbellone** [poise/poise-service#4]
@acaiafa has been working on building out our [nginx cookbook](https://github.com/bloomberg/nginx-cookbook) using poise and poise-service. During our testing on Ubuntu (and seemingly, Systemd) we ran into a problem where we need to be able to add additional options to the default templates provided in poise-service.

This shouldn't be a problem, but we want to avoid having to have a switch-case for each platform to specify the source changes. The suggestion that we came up with is allowing the service options resource to accept a cookbook_name attribute which defaults to poise-service. This allows us to simply create the same filenames only in the nginx cookbook for the changes we need.

The example that we need to support is the ability to add forking functionality.

**Comment by coderanger** [comment]
The `service_template` helper does some magic stuffs for this: https://github.com/poise/poise-service/blob/master/lib/poise_service/service_providers/base.rb#L154-L168

It you override the template, it defaults to using the template the `poise_service` instance is in, but you can override that via `'cookbook:template'` in the option.

Is this the kind of thing you are talking about? You should be able to specify the override inside your poise-service instance like this:

```ruby
poise_service 'nginx' do
  command 'whatever'
  options :systemd, template: 'nginx.unit.erb'
end
```

or something like that

**Comment by johnbellone** [comment]
@acaiafa will give it a whirl and we'll let you know.

**Comment by acaiafa** [comment]
/cc @johnbellone spoke with noah

https://github.com/acaiafa/nginx-cookbook/commit/f6431eca78f2236d50b03b42d6e1f130068518a2

**Comment by coderanger** [comment]
Going to close this out, everything looks good on the nginx side. At some point in the future it would be good to revisit how to deal with extending the default templates without copy-pasta but that's a systemic issue in Chef.
