### ISSUE TITLE
Which versions of chef-client does this support?

### ISSUE THREAD

**Issue by skingsland** [poise/poise-service#41]
I'm stuck on chef-client 11.18, and I'm guessing poise-service requires 12+. Is there somewhere that's explicitly stated? I checked the README and supermarket page for this cookbook, but didn't see anything.

If I wanted to use poise-service with chef 11.18, is there an older version that supports it?

**Comment by coderanger** [comment]
All of my cookbooks only support Chef 12.x, which should be enforced automatically via the cookbook metadata. There is no version for 11.x as that version was already long-since functionally dead when this cookbook was started :)

**Comment by skingsland** [comment]
Thanks for the quick reply, that's kind of what I figured.

Is there some way I could have discovered that fact, somewhere that requirement is stated? You said it "should be enforced automatically via the cookbook metadata", but I couldn't find any metadata in either poise-service or poise itself that clarified this. Can you give me a link?

**Comment by coderanger** [comment]
It's a [default value for all Halite-based cookbooks](https://github.com/poise/halite/blob/master/lib/halite/converter/metadata.rb#L50) so the place it would show up is the generated cookbook itself. I note in my READMEs when I need something more than 12.0 but 11.x is end-of-life'd in many many ways (Chef, Ruby, OpenSSL, running it should be considered negligent at this point) so I don't document anything about it.
