### ISSUE TITLE
Any way to make the service template sensitive?

### ISSUE THREAD

**Issue by mitom** [poise/poise-service#45]
Occasionally the service requires some sort of credentials (like a token) which is to be passed in an argument or as an environment variable. Both of these would then live in the service definition. While this is admittedly not the best, sometimes it's just impossible to avoid writing the credentials to file. It would be somewhat of an improvement if we could mark the template as sensitive (or the service which would then mark the template..?) and avoid these credentials leaking into the chef logs at least.

**Comment by coderanger** [comment]
The easiest option would be a custom subclass of whichever provider you're using. This is niche enough I probably wouldn't add it to poise-service itself so I would go that route.

**Comment by coderanger** [comment]
A better solution might be to use some kind of wrapper script which contains the secret bits.

**Comment by mitom** [comment]
You are right, a wrapper script is probably the best solution.
