### ISSUE TITLE
Is the project alive?

### ISSUE THREAD

**Issue by dragonsmith** [poise/poise-service#50]
Hello @coderanger!

Is it ok to check if this project is alive and maintained? I'm bothered because the last commit was more than a year ago, and I see issues dating back to 2017.

Do you plan to support this cookbook any further?

We are deciding if we should use your cookbook as a dependency for ours (https://github.com/evilmartians/chef-prometheus-exporters/pull/22). The liveness of the project seems to me like a decent metric among others.

Thank you very much!

**Comment by coderanger** [comment]
Barely. I no longer use Chef and do not wish to associate with the community due to Chef Software Inc. I recommend finding replacements for my projects, though I will maybe fix them if there is substantial breakage with truly no workarounds.

**Comment by dragonsmith** [comment]
Thanks!

**Comment by aprice** [comment]
This should really be noted at the top of the readme, not hidden in a closed issue.
