### ISSUE TITLE
Metadata.rb file are missing from source control

### ISSUE THREAD

**Issue by poliva83** [poise/poise-service#6]
Can the `metadata.rb` file can be added to this cookbook? I have a script that mirrored this repo internally but `berks` complains when trying to use mirrored git location as cookbook rule in top-level cookbook `Berksfile`.

It works when you get it from supermarket because for some reason the `metadata.rb` and `metadata.json` files are getting added before you push cookbook there.

The same issue affects `poise-ruby` and `poise` cookbooks.

Related
https://github.com/poise/poise-ruby/issues/8
https://github.com/poise/poise/issues/22

**Comment by coderanger** [comment]
No, this cookbook is managed via Halite. See https://github.com/poise/halite#using-a-pre-release-version-of-a-cookbook for info on how to run from git directly.
