### ISSUE TITLE
ChefSpec?

### ISSUE THREAD

**Issue by phs** [poise/poise-service#7]
`poise-service` looks great.  I'd like to write some chefspec unit tests for recipes that incorporate it.  Are there custom matchers somewhere I can/should use?

**Comment by coderanger** [comment]
They are created automatically by Poise for all actions :-) Just use the standard format like `enable_poise_service('name').with(command: 'whatever')` and it should JFW.

**Comment by phs** [comment]
Delightful!  Thank you.

**Comment by phs** [comment]
Hm.  I think I'm still missing something that is probably obvious (apologies in advance: I'm new to chef, but not to ruby.)

Imitating this [line](https://github.com/poise/application_javascript/blob/4a934ec/test/spec/resources/npm_start_spec.rb#L37), I'm trying:

```
it { is_expected.to enable_poise_service('the-service') }
```

but I receive

```
1) cookbook::recipe via solo creates the service
   Failure/Error: is_expected.to enable_poise_service('the-service')
   NoMethodError:
     undefined method `enable_poise_service' for #<RSpec::ExampleGroups::CookbookRecipe::ViaSolo:0x007f98a1667628>
   # ./spec/recipe_spec.rb:31:in `block (3 levels) in <top (required)>'
```

I assume I'm just missing something from `spec_helper.rb` or similar.  Following [your example](https://github.com/poise/application_javascript/blob/4a934ec/test/spec/spec_helper.rb#L17-L18), however, only reveals that the two named files appear absent from my load path.

My `Berksfile` includes `cookbook 'poise-service', '~> 1.0.2'`, however my `Gemfile` does not directly mention `poise` in any way.

Any tips for the poor noob?

**Comment by phs** [comment]
I was obliged to `require 'poise_service/resources'` in `spec_helper` after requiring `chefspec` to get the `enable_poise_service` matcher to appear.

**Comment by phs** [comment]
Ah!  I forgot the `depends 'poise-service'` in `metadata.rb`.  With that the other hacks are unnecessary.

**Comment by coderanger** [comment]
That would do it :)
