### ISSUE TITLE
`Process.uid = some_user` not working on Centos 6 + upstart

### ISSUE THREAD

**Issue by NickLaMuro** [poise/poise-service#8]
Description
---------------
When using older versions of upstart, the `Process.uid = your_poise_service_user` doesn't seem to de-escalate privileges properly, and causes errors when spawning the process.

I have created a sample repo here to illustrate the issue with a dummy ruby process being spawned from a poise service:

https://gist.github.com/NickLaMuro/6c250cb8dc0ae5c8b0cb

Potential solution
-----------------------
When using `Process::UID.change_privilege`, the process spawns properly and without error.  This might be the simplest solution, but I am not sure of the portability of that versus `Process.uid=` and if it exists on most versions of ruby.

Let me know if you need me to explain things further or code up a PR to address the issue.

**Comment by coderanger** [comment]
I'm trying to figure out why `Process.uid=` results in `$SAFE` getting set but `Process::UID` doesn't. The change is reasonable but I don't grok why it would matter. SAFE mode is normally only enabled when Ruby is running setuid, so I would bet my trickery with exec has something to do with it. Let me research a bit more.

**Comment by NickLaMuro** [comment]
No worries.  I am kinda in the same boat which is why I didn't jump to making a PR.

I am able to work around it for now since I can just write my own template that just uses `Process::UID`, so no rush on getting this out.

Thanks!

**Comment by NickLaMuro** [comment]
@coderanger For what it is worth, this might also have something to do with it:

```
[vagrant@default ~]$ sudo -s
[root@default vagrant]# /opt/chef/embedded/bin/ruby -e 'Process.uid = "deploy"; puts [Process.uid, Process.euid]'
497
0
[root@default vagrant]# /opt/chef/embedded/bin/ruby -e 'Process::UID.change_privilege "deploy"; puts [Process.uid, Process.euid]'
497
497
[root@vk-app vagrant]#
```

`Process.uid=` doesn't seem to change the `euid` when it changes the `uid`, where as `Process::UID.change_privilege` does.  I am far from an expert on the subject, but that might be what is causing the problems from a Ruby perspective at least.

**Comment by coderanger** [comment]
Yeah, I agree that is likely related and makes `change_privilege` a better solution, but I still can't repro the issue:

```
$ PATH="/opt/chef/embedded/bin:/usr/local/bin:/usr/bin:/bin:$PATH" /opt/chef/embedded/bin/ruby -e 'Process.uid = "kitchen"; ENV["HOME"] = Dir.home("kitchen") rescue nil; exec(*["/opt/chef/embedded/bin/bundle", "exec", "/opt/chef/embedded/bin/ruby", "-run", "-e", "p $SAFE"])'
0
```

**Comment by coderanger** [comment]
Okay, got it to repro locally and adding `Process.euid=` does fix it too so that's definitely the issue but I think your solution is better. Will get it pushed shortly. Thanks for the deep investigation!

**Comment by NickLaMuro** [comment]
Cool cool, and no prob, I was pounding my head against the wall a day ago trying to figure this out myself, so I am happy it won't cause problems for others!

Thanks again!
