### ISSUE TITLE
User's home creation

### ISSUE THREAD

**Issue by jmauro** [poise/poise-service#9]
Hey,

I am trying to use the 'poise_user' provider but this user doesn't seem to handle home creation, I wonder why aren't you using the possibility to use the 'user' attribute 'manage_home'. Is that on purpose?

Would that make sense to create a PR to give that kind of configuration?

Regards,
JM

**Comment by coderanger** [comment]
`poise_service_user` exists specifically for service accounts, which generally don't have a traditional home directory as they are not intended for a human to ever use directly.

**Comment by jmauro** [comment]
Hey,

True in most case but the daemon could use this directory as a data
directory don't you think? Like /var/lib/mysql for instance? The shell
limits the use if the account.

**Comment by coderanger** [comment]
That kind of directory would be created by your Chef code, not via the user skel creation system. You can set the home dir for a service user, you just can't populate it from skel.

**Comment by jmauro** [comment]
Fair enough.

Thx for answering
